### ISSUE TITLE
Native Image and GRPC class loading issue

### ISSUE THREAD

**Issue by medgar-nitric** [nitrictech/java-sdk#83]
Failed to execute a native compiled function with GRPC classloading issues

```
Registered Gateway Plugin
Starting Child Process
Services listening on: 127.0.0.1:50051
Waiting for active workers
Received init request from worker
Starting Worker Supervisor
Starting Gateway, 1 workers currently available
Nov 12, 2021 11:55:23 PM io.nitric.faas.logger.JUtilLogger error
SEVERE: error handling Trigger HTTP GET '/examples' with: function.List$$Lambda$6dba56083d66a5a29b7002ed773185b38c97ac24
java.lang.ExceptionInInitializerError
at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315)
at io.nitric.proto.document.v1.DocumentQueryRequest$PagingTokenDefaultEntryHolder.<clinit>(DocumentQueryRequest.java:256)
at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
at io.nitric.proto.document.v1.DocumentQueryRequest$Builder.internalGetPagingToken(DocumentQueryRequest.java:1303)
at io.nitric.proto.document.v1.DocumentQueryRequest$Builder.buildPartial(DocumentQueryRequest.java:674)
at io.nitric.proto.document.v1.DocumentQueryRequest$Builder.build(DocumentQueryRequest.java:648)
at io.nitric.api.document.QueryResults.buildDocQueryRequest(QueryResults.java:123)
at io.nitric.api.document.QueryResults.<init>(QueryResults.java:64)
at io.nitric.api.document.Query.stream(Query.java:387)
at function.List.lambda$main$0(List.java:21)
at io.nitric.faas.http.HttpMiddleware$HandlerAdapter.handle(HttpMiddleware.java:102)
at io.nitric.faas.TriggerProcessor$HttpMiddlewareWrapper.handle(TriggerProcessor.java:310)
at io.nitric.faas.TriggerProcessor.processHttpTrigger(TriggerProcessor.java:123)
at io.nitric.faas.TriggerProcessor.process(TriggerProcessor.java:94)
at io.nitric.faas.FaasStreamObserver.onNext(FaasStreamObserver.java:82)
at io.nitric.faas.FaasStreamObserver.onNext(FaasStreamObserver.java:39)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:465)
at io.grpc.internal.DelayedClientCall$DelayedListener.onMessage(DelayedClientCall.java:448)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:652)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:637)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:829)
at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.RuntimeException: Generated message class "com.google.protobuf.DescriptorProtos$FieldOptions" missing method "getCtype".
at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1847)
at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.<init>(GeneratedMessageV3.java:2176)
at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessageV3.java:2248)
at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularEnumFieldAccessor.<init>(GeneratedMessageV3.java:2743)
at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:1973)
at com.google.protobuf.DescriptorProtos$FieldOptions.internalGetFieldAccessorTable(DescriptorProtos.java:28861)
at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133)
at com.google.protobuf.GeneratedMessageV3$ExtendableMessage.parseUnknownField(GeneratedMessageV3.java:1134)
at com.google.protobuf.DescriptorProtos$FieldOptions.<init>(DescriptorProtos.java:28831)
at com.google.protobuf.DescriptorProtos$FieldOptions.<init>(DescriptorProtos.java:28730)
at com.google.protobuf.DescriptorProtos$FieldOptions$1.parsePartialFrom(DescriptorProtos.java:30815)
at com.google.protobuf.DescriptorProtos$FieldOptions$1.parsePartialFrom(DescriptorProtos.java:30809)
at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:888)
at com.google.protobuf.DescriptorProtos$FieldDescriptorProto.<init>(DescriptorProtos.java:11697)
at com.google.protobuf.DescriptorProtos$FieldDescriptorProto.<init>(DescriptorProtos.java:11589)
at com.google.protobuf.DescriptorProtos$FieldDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:14349)
at com.google.protobuf.DescriptorProtos$FieldDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:14343)
at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:888)
at com.google.protobuf.DescriptorProtos$DescriptorProto.<init>(DescriptorProtos.java:5228)
at com.google.protobuf.DescriptorProtos$DescriptorProto.<init>(DescriptorProtos.java:5164)
at com.google.protobuf.DescriptorProtos$DescriptorProto$1.parsePartialFrom(DescriptorProtos.java:10295)
at com.google.protobuf.DescriptorProtos$DescriptorProto$1.parsePartialFrom(DescriptorProtos.java:10289)
at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:888)
at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1281)
at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1201)
at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:4888)
at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:4882)
at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
at com.google.protobuf.DescriptorProtos$FileDescriptorProto.parseFrom(DescriptorProtos.java:2297)
at com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(Descriptors.java:410)
at io.nitric.proto.document.v1.Documents.<clinit>(Documents.java:174)
at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
... 27 more
Caused by: java.lang.NoSuchMethodException: com.google.protobuf.DescriptorProtos$FieldOptions.getCtype()
at java.lang.Class.getMethod(DynamicHub.java:1120)
at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1844)
... 64 more

```

**Comment by medgar-nitric** [comment]
Worth testing whether adding `reflect-config.json` to API can resolve this issue:

```
src/main/resources/META-INF/native-image/reflect-config.json
```

For example:

```
 [
    {
       "name" : "io.nitric.proto.document.v1.DocumentQueryRequest$PagingTokenDefaultEntryHolder",
       "allDeclaredConstructors" : true,
       "allPublicConstructors" : true,
       "allDeclaredMethods" : true,
       "allPublicMethods" : true,
       "allDeclaredFields" : true,
       "allPublicFields" : true
    }
]
```
